name:  simple ci to build, push and run docker container from github action

on: [push]

jobs:
 build:
  runs-on: ${{os}}
  strategy:
   matrix:
    os: [ubuntu-latest, windows-latest, macOs-latest]
  steps:
   - uses: actions/checkout@v2
   - name: building the docker image 
     run: |
      docker pull chef/chefdk
   - name: Building the docker container
     run: |
      docker run -d --name=chef chef/chefdk
